#!/bin/sh
alias j='z'
alias f='zi'
alias g='lazygit'
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"

alias .nvim='nvim ~/.config/nvim/'
alias .i3='nvim ~/.config/i3/'
alias .alacritty='nvim ~/.config/alacritty/'
alias .kitty='nvim ~/.config/kitty/'
alias .rofi='nvim ~/.config/rofi/'
alias .polybar='nvim ~/.config/polybar/'
alias .zsh='nvim ~/.config/zsh/'


alias config='cd ~/.config/'
alias h='cd ~'

alias v='nvim '
alias v.='nvim .'

alias dev="~/Sandbox/"
alias js="~/Sandbox/js/"
alias css="~/Sandbox/css/"
alias html="~/Sandbox/html"
alias angular="~/Sandbox/angular/"
alias react="~/Sandbox/react/"
alias vue="~/Sandbox/vue/"



# get fastest mirrors
alias mirror="sudo reflector -f 30 -l 30 --number 10 --verbose --save /etc/pacman.d/mirrorlist"
alias mirrord="sudo reflector --latest 50 --number 20 --sort delay --save /etc/pacman.d/mirrorlist"
alias mirrors="sudo reflector --latest 50 --number 20 --sort score --save /etc/pacman.d/mirrorlist"
alias mirrora="sudo reflector --latest 50 --number 20 --sort age --save /etc/pacman.d/mirrorlist"

# Colorize grep output (good for log files)
alias grep='grep --color=auto'
alias egrep='egrep --color=auto'
alias fgrep='fgrep --color=auto'

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# easier to read disk
alias df='df -h'     # human-readable sizes
alias free='free -m' # show sizes in MB

# get top process eating memory
alias psmem='ps auxf | sort -nr -k 4 | head -5'

# get top process eating cpu ##
alias pscpu='ps auxf | sort -nr -k 3 | head -5'


# For when keys break
alias archlinx-fix-keys="sudo pacman-key --init && sudo pacman-key --populate archlinux && sudo pacman-key --refresh-keys"

# systemd
alias mach_list_systemctl="systemctl list-unit-files --state=enabled"


alias m="git checkout master"
alias s="git checkout stable"

alias l='ls -al --color=auto'
alias ls='exa -al --color=always --icons --group-directories-first' # my preferred listing
alias la='exa -a --color=always --group-directories-first'  # all files and dirs
alias ll='exa -l --color=always --group-directories-first'  # long format
alias lt='exa -aT --color=always --group-directories-first' # tree listing
alias l.='exa -a | egrep "^\."'


alias pacman='sudo pacman --color auto'
alias update='sudo pacman -Syyu'

alias cleanup='sudo pacman -Rns $(pacman -Qtdq)'

# paru as aur helper - updates everything
alias pksyua="paru -Syu --noconfirm"
alias upall="paru -Syu --noconfirm"

alias tobash="sudo chsh $USER -s /bin/bash && echo 'Now log out.'"
alias tozsh="sudo chsh $USER -s /bin/zsh && echo 'Now log out.'"

alias kc='killall conky'
alias kp='killall polybar'
alias ssn="sudo shutdown now"
alias sr="sudo reboot"



alias yta-aac="yt-dlp --extract-audio --audio-format aac "
alias yta-best="yt-dlp --extract-audio --audio-format best "
alias yta-flac="yt-dlp --extract-audio --audio-format flac "
alias yta-mp3="yt-dlp --extract-audio --audio-format mp3 "
alias ytv-best="yt-dlp -f 'bestvideo[ext=mp4]+bestaudio[ext=m4a]/bestvideo+bestaudio' --merge-output-format mp4 "


alias r="ranger ."
alias e="thunar ."
alias caps="setxkbmap -layout us -option caps:escape"
alias ucaps="setxkbmap -layout us -option caps:caps"
alias n="nvm"
alias d=". /home/prajith/.screenlayout/dual.sh"
alias m=". /home/prajith/.screenlayout/single.sh"
alias e=". /home/prajith/.screenlayout/external.sh"
